approve_by_comment: true
approve_regex: '^[Aa]pprovato'
reject_regex: '^[Rr]igettato'
reset_on_push: true
reviewers:
  -
    name: administrators
    members:
    - trenta3
    required: 1
    conditions:
      branches:
      - master

  -
    name: reviewers
    members: all
    required: 1
    conditions:
      branches:
      - master

