language: ruby
rvm:
- 2.2

branches:
  only:
  - master

before_install:
    - sudo apt-get -yq update
    - sudo apt-get -y install texlive-latex-base texlive-base texlive-lang-italian latexmk ruby-dev ruby
    - sudo apt-get -y install texlive-fonts-extra texlive-latex-recommended coreutils

install: gem install kramdown

script:
# Creiamo la cartella dei pdf compilati
- mkdir -p ../compiled-pdfs/
# Compiliamo il pdf delle lezioni complete se siamo nel branch master
- latexmk -pdf lezioni.tex && cp lezioni.pdf ../compiled-pdfs/Zannier1617-$( date +'%y%m%d%H%M%S' | tr -d '\n' ).pdf
# Inoltre creiamo la pagina iniziale del "sito internet" del repository dall'INDEX.md
- cp INDEX.md ../compiled-pdfs/
- cp -r .site/public ../compiled-pdfs/
- cp .site/indexing ../compiled-pdfs/
- ../compiled-pdfs/indexing

deploy:
  skip_cleanup: true
  provider: surge
  project: ../compiled-pdfs/
  domain: zannier1617.surge.sh
